export const dataActionTypes = {
  SET_GENDER: 'SET_GENDER',
  SET_BIRTH: 'SET_BIRTH',
  SET_STATUS: 'SET_STATUS',
  SET_PARENT: 'SET_PARENT',
  SET_PROBLEMS: 'SET_PROBLEMS',
  SET_SINGLE_PARENT: 'SET_SINGLE_PARENT',
  SET_DECISIONS: 'SET_DECISIONS',
  SET_EMAIL: 'SET_EMAIL',
};

export default dataActionTypes;
